version: 2.1
aliases:
  - &root-yarn |
    yarn install --non-interactive --cache-folder ~/.cache/yarn

  - &root-restore-yarn-cache
    keys:
      - root-yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - root-yarn-{{ .Branch }}-

  - &root-save-yarn-cache
    paths:
      - node_modules
      - ~/.cache/yarn
    key: root-yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}

defaults: &defaults
  docker:
    - image: circleci/node:10.15.1

jobs:
  lint:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *root-restore-yarn-cache
      - run: *root-yarn
      - save_cache: *root-save-yarn-cache
      - run:
          name: Lint
          command: yarn lint
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *root-restore-yarn-cache
      - run: *root-yarn
      - save_cache: *root-save-yarn-cache
      - run:
          name: Test
          command: yarn test:ci

workflows:
  lint:
    jobs:
      - lint
  test:
    jobs:
      - test
